server:
  port: 8080
  servlet: 
    session:
      timeout: 7200 
  tomcat: 
    max-threads: 5 #减少tomcat线程数
      
spring:
  application:
    name: nginx配置器
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      
  devtools:
    restart:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jmx:
    enabled: true 
  database: 
    type: sqlite
    package: com.cym.model
    print: true
    sqlite-path: ${project.home}sqlite.db 

project:
  version: v@project.version@
  home: /home/nginxWebUI/
  
logging: 
  file:    name: ${project.home}log/nginxWebUI.log
  level: 
    root: info
  
