server:
  port: 8080
  servlet: 
    session:
      timeout: 7200 
  tomcat:
    # 默认是200
    threads:
      max: 5 #减少tomcat线程数
spring:
  application:
    name: nginxWebUI
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  jackson:
    default-property-inclusion: NON_NULL
  jmx:
    enabled: true 
  database: 
    type: sqlite
    package: com.cym.model
    print: false
    sqlite-path: ${project.home}sqlite.db

project:
  version: v@project.version@
  home: /home/nginxWebUI/
  
logging: 
  file:
    name: ${project.home}log/nginxWebUI.log
    max-size: 1024MB
  level: 
    root: info

knife4j:
  enable: true
  production: true # 生产环境屏蔽